//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 04:46:37 PM IST 
//


package com.tracker.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Xml }
     * 
     */
    public Xml createXml() {
        return new Xml();
    }

    /**
     * Create an instance of {@link Xml.Passengers }
     * 
     */
    public Xml.Passengers createXmlPassengers() {
        return new Xml.Passengers();
    }

    /**
     * Create an instance of {@link Xml.FromStation }
     * 
     */
    public Xml.FromStation createXmlFromStation() {
        return new Xml.FromStation();
    }

    /**
     * Create an instance of {@link Xml.ToStation }
     * 
     */
    public Xml.ToStation createXmlToStation() {
        return new Xml.ToStation();
    }

    /**
     * Create an instance of {@link Xml.ReservationUpto }
     * 
     */
    public Xml.ReservationUpto createXmlReservationUpto() {
        return new Xml.ReservationUpto();
    }

    /**
     * Create an instance of {@link Xml.BoardingPoint }
     * 
     */
    public Xml.BoardingPoint createXmlBoardingPoint() {
        return new Xml.BoardingPoint();
    }

    /**
     * Create an instance of {@link Xml.Passengers.Passenger }
     * 
     */
    public Xml.Passengers.Passenger createXmlPassengersPassenger() {
        return new Xml.Passengers.Passenger();
    }

}
